# Generated by Django 4.2.5 on 2024-02-13 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_remove_deliveryboy_user_alter_customuser_role_and_more'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='driving_license',
            field=models.FileField(null=True, unique=True, upload_to='driving_licenses/'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveryBoyEdit',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('driving_license', models.FileField(null=True, unique=True, upload_to='driving_licenses/')),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='vet_profile_photos/')),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.deliveryboy')),
            ],
        ),
    ]
