# Generated by Django 4.2.5 on 2024-02-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_deliveryboy_driving_license_deliveryboy_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboyedit',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyedit',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyedit',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyedit',
            name='house_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
