# Generated by Django 4.2.5 on 2024-02-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_deliveryboyedit_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.deliveryboy')),
            ],
        ),
    ]
