# Generated by Django 4.2.5 on 2023-10-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('CattleId', models.AutoField(primary_key=True, serialize=False)),
                ('EarTagID', models.PositiveIntegerField()),
                ('CattleType', models.CharField(max_length=10)),
                ('BreedName', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Colour', models.CharField(max_length=50)),
                ('HealthStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerNo', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNo', models.PositiveIntegerField()),
                ('CustomerName', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('CardNo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('FarmerId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('HouseName', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('PinCode', models.PositiveIntegerField()),
                ('Occupation', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('RationcardNo', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('AccNo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('Societycode', models.AutoField(primary_key=True, serialize=False)),
                ('District', models.CharField(max_length=20)),
                ('Subdistrict', models.CharField(max_length=50)),
                ('Panchayath', models.CharField(max_length=50)),
                ('WardNo', models.PositiveIntegerField()),
                ('FarmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='MilkingCattle',
            fields=[
                ('Cattleid', models.AutoField(primary_key=True, serialize=False)),
                ('CattleType', models.CharField(max_length=50)),
                ('FarmerId', models.PositiveIntegerField()),
                ('Eartagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('CattleId', models.AutoField(primary_key=True, serialize=False)),
                ('Height', models.PositiveIntegerField()),
                ('Weight', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Feed', models.CharField(max_length=50)),
                ('Medicine', models.CharField(max_length=50)),
                ('MilkObtainedPerDay', models.PositiveIntegerField()),
                ('HealthStatus', models.CharField(max_length=50)),
                ('FarmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='Societycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.society'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='FarmerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('BreedId', models.AutoField(primary_key=True, serialize=False)),
                ('BreedName', models.CharField(max_length=50)),
                ('EarType', models.CharField(max_length=50)),
                ('Height', models.PositiveIntegerField()),
                ('CattleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('IFSCcode', models.AutoField(primary_key=True, serialize=False)),
                ('Bankname', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Accno', models.PositiveIntegerField()),
                ('FarmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
