# Generated by Django 4.2.5 on 2024-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
