# Generated by Django 4.2.5 on 2024-04-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_meeting_meeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.IntegerField(default=0)),
                ('agenda', models.TextField()),
                ('description', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.meeting')),
            ],
        ),
    ]
