# Generated by Django 4.2.5 on 2023-11-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_name', models.CharField(max_length=50)),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('grade_level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('upload_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.CharField(choices=[('Milk', 'Milk'), ('Curd', 'Curd'), ('Paneer', 'Paneer'), ('Ghee', 'Ghee'), ('Butter', 'Butter'), ('Cheese', 'Cheese')], default='milk', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle', models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo'), ('Goat', 'Goat')], default='Cow', max_length=10)),
                ('collection_date', models.DateField()),
                ('collection_time', models.CharField(choices=[('1', 'ForeNoon'), ('2', 'AfterNoon')], default='1.027-1.03', max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('density_level', models.CharField(choices=[('1', '1.03+'), ('2', '1.027-1.03'), ('3', '1.03-')], default='1.027-1.03', max_length=10)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
            ],
        ),
    ]
