# Generated by Django 4.2.5 on 2023-11-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_name', models.CharField(max_length=50)),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('grade_level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('Description', models.TextField()),
                ('categories', models.CharField(choices=[('Milk', 'Milk'), ('Curd', 'Curd'), ('Paneer', 'Paneer'), ('Ghee', 'Ghee'), ('Butter', 'Butter'), ('Cheese', 'Cheese')], default='milk', max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='products/')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
            ],
        ),
    ]
