# Generated by Django 4.2.5 on 2023-11-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_customuser_is_customer'),
        ('product', '0002_rename_description_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collection_time', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('density_level', models.CharField(choices=[('1', '1.03+'), ('2', '1.027-1.03'), ('3', '1.03-')], default='1.027-1.03', max_length=10)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
            ],
        ),
    ]
