# Generated by Django 4.2.5 on 2023-10-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_category',
            name='seller',
        ),
    ]
