# Generated by Django 4.2.5 on 2023-12-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grade_level',
        ),
    ]
