# Generated by Django 4.2.5 on 2023-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_milkcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='collection_time',
            field=models.CharField(choices=[('1', 'ForeNoon'), ('2', 'AfterNoon')], default='1.027-1.03', max_length=50),
        ),
    ]
