# Generated by Django 4.2.5 on 2023-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_milkcollection_collection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='cattle',
            field=models.CharField(choices=[('1', 'Cow'), ('2', 'Buffalo'), ('3', 'Goat')], default='1', max_length=10),
        ),
    ]
