# Generated by Django 4.2.5 on 2023-12-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkcollection',
            old_name='cattle',
            new_name='milk_type',
        ),
        migrations.RenameField(
            model_name='milkcollection',
            old_name='density_level',
            new_name='quality_test_report',
        ),
    ]
