# Generated by Django 4.2.5 on 2023-11-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_milkcollection_cattle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='cattle',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo'), ('Goat', 'Goat')], default='Cow', max_length=10),
        ),
    ]
