# Generated by Django 4.2.5 on 2023-12-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_cattle_milkcollection_milk_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='quality_test_report',
            field=models.CharField(choices=[('density-level above 1.03', 'density-level above 1.03'), ('density-level between 1.027-1.03', 'density-level between 1.027-1.03'), ('density-level below 1.03', 'density-level below 1.03')], default='1.027-1.03', max_length=50),
        ),
    ]
