# Generated by Django 4.2.5 on 2024-02-14 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_milkcollection_quality_test_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cow', 'Cow Milk'), ('Goat', 'Goat Milk'), ('Buffalo', 'Buffalo Milk')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('density', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bacterial_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('antibiotic_residue', models.CharField(max_length=50)),
                ('freezing_point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('somatic_cell_count', models.PositiveIntegerField()),
                ('lactose_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_test_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
