# Generated by Django 4.2.5 on 2023-11-09 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_wishlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
