# Generated by Django 4.2.5 on 2024-02-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_sampletestreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampletestreport',
            old_name='antibiotic_residue',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='sampletestreport',
            old_name='freezing_point',
            new_name='turbidity',
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='status',
        ),
    ]
