# Generated by Django 4.2.5 on 2023-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_upload_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade_level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10),
        ),
    ]
