# Generated by Django 4.2.5 on 2024-02-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_cart_price_cart_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_successful',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
