# Generated by Django 4.2.5 on 2024-03-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_delivery_address_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
