# Generated by Django 4.2.5 on 2024-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
