# Generated by Django 4.2.5 on 2024-04-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0036_deliveryboyeditprofile_age_and_more'),
        ('product', '0019_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.deliveryboy'),
        ),
    ]
