# Generated by Django 4.2.5 on 2024-04-04 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0037_appointment_time'),
        ('product', '0020_order_delivery_boy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampletestreport',
            old_name='bacterial_content',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='sampletestreport',
            old_name='density',
            new_name='pH',
        ),
        migrations.RenameField(
            model_name='sampletestreport',
            old_name='fat_content',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='milkcollection',
            name='quality_test_report',
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='lactose_content',
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='protein_content',
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='somatic_cell_count',
        ),
        migrations.AddField(
            model_name='sampletestreport',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sampletestreport',
            name='color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampletestreport',
            name='odor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampletestreport',
            name='taste',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampletestreport',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_test_reports', to='farm.seller'),
        ),
    ]
