# Generated by Django 4.2.5 on 2024-04-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_rename_bacterial_content_sampletestreport_fat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkcollection',
            name='price',
        ),
    ]
