# Generated by Django 4.2.5 on 2024-04-04 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0037_appointment_time'),
        ('product', '0023_alter_sampletestreport_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_time', models.CharField(choices=[('ForeNoon', 'ForeNoon'), ('AfterNoon', 'AfterNoon')], default='ForeNoon', max_length=50)),
                ('milk_type', models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo'), ('Goat', 'Goat')], default='Cow', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('pH', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('taste', models.CharField(max_length=50, null=True)),
                ('odor', models.CharField(max_length=50, null=True)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('turbidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_samples', to='farm.seller')),
            ],
        ),
        migrations.RemoveField(
            model_name='sampletestreport',
            name='seller',
        ),
        migrations.DeleteModel(
            name='MilkCollection',
        ),
        migrations.DeleteModel(
            name='SampleTestReport',
        ),
    ]
