# Generated by Django 4.2.5 on 2024-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_milksample_remove_sampletestreport_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksample',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
