# Generated by Django 4.2.5 on 2024-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_milksample_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksample',
            name='color',
            field=models.CharField(help_text='This Column defines Colour of the milk which ranges from 240 to 255 max : 255', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='description',
            field=models.TextField(help_text='Enter the description'),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='fat',
            field=models.DecimalField(decimal_places=2, help_text='This Column defines Odor of the milk which is categorical data 0 (Low) or 1 (High) max : 1 (High)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='grade',
            field=models.CharField(blank=True, help_text='This Column defines Grade (Target) of the milk which is categorical data Where Low (Bad) or Medium (Moderate) High', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='odor',
            field=models.CharField(help_text='This Column defines Odor of the milk which is categorical data 0 (Bad) or 1 (Good) max : 0 (Bad', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='pH',
            field=models.DecimalField(decimal_places=2, help_text='This Column defines PH values of the milk which ranges from 3 to 9.5 max : 6.25 to 6.90', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity of milk in liters'),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='taste',
            field=models.CharField(help_text='This Column defines Taste of the milk which is categorical data 0 (Bad) or 1 (Good) max : 1 (Good)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text="This Column defines Temprature of the milk which ranges from 34'C to 90'C max : 34'C to 45.20'C", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='turbidity',
            field=models.DecimalField(decimal_places=2, help_text='This Column defines Turbidity of the milk which is categorical data 0 (Low) or 1 (High) max : 1 (High)', max_digits=5, null=True),
        ),
    ]
