# Generated by Django 4.2.5 on 2024-04-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_milksample_color_alter_milksample_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksample',
            name='color',
            field=models.CharField(help_text="<span style='color: green;'>This Column defines Color of the milk which ranges from 240 to 255 max : 255</span>", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='fat',
            field=models.DecimalField(decimal_places=2, help_text="<span style='color: green;'>This Column defines Fat of the milk which is categorical data 0 (Low) or 1 (High) max : 1 (High)</span>", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='grade',
            field=models.CharField(blank=True, help_text="<span style='color: green;'>This Column defines Grade (Target) of the milk which is categorical data Low (Bad) or Medium (Moderate) High</span>", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='odor',
            field=models.CharField(help_text="<span style='color: green;'>This Column defines Odor of the milk which is categorical data 0 (Bad) or 1 (Good) max : 0 (Bad)</span>", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='pH',
            field=models.DecimalField(decimal_places=2, help_text="<span style='color: green;'>This Column defines PH values of the milk which ranges from 3 to 9.5 max : 6.25 to 6.90</span>", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='taste',
            field=models.CharField(help_text="<span style='color: green;'>This Column defines Taste of the milk which is categorical data 0 (Bad) or 1 (Good) max : 1 (Good)</span>", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text="<span style='color: green;'>This Column defines Temperature of the milk which ranges from 34'C to 90'C max : 34'C to 45.20'C</span>", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='milksample',
            name='turbidity',
            field=models.DecimalField(decimal_places=2, help_text="<span style='color: green;'>This Column defines Turbidity of the milk which is categorical data 0 (Low) or 1 (High) max : 1 (High)</span>", max_digits=5, null=True),
        ),
    ]
