# Generated by Django 4.2.5 on 2023-11-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin')], max_length=15)),
                ('forget_password_token', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CattleType',
            fields=[
                ('name', models.CharField(choices=[('cow', 'COW'), ('goat', 'GOAT'), ('buffalo', 'BUFFALO')], default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=hidden')),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IFSCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('ifsccode', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_code', models.CharField(default='default_value_here', max_length=20)),
                ('district', models.CharField(default='', max_length=20)),
                ('subdistrict', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='default_location', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cattle_license', models.CharField(default=False, max_length=10, unique=True)),
                ('EarTagID', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Colour', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=50)),
                ('milk_obtained', models.IntegerField()),
                ('vaccination', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cattle_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('card_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Your_Profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('farmer_license', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=hidden')),
                ('cattle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cattletype')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='farm.customgroup'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField()),
                ('administered_by', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='farm.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='SellerEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(blank=True, default=None, null=True)),
                ('occupation', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('rationcard_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('acc_no', models.IntegerField(null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='seller_profile_photos/')),
                ('farmer_license', models.CharField(max_length=50)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farm.society')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_info', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='farm.cattle')),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='BreedName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.breed'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='CattleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cattletype'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seller'),
        ),
    ]
