# Generated by Django 4.2.5 on 2023-11-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='society',
            old_name='panchayath',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='society',
            name='subdistrict',
        ),
    ]
