# Generated by Django 4.2.5 on 2023-11-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Normal', 'Normal'), ('Unhealthy', 'Unhealthy')], default='Healthy', max_length=50),
        ),
    ]
