# Generated by Django 4.2.5 on 2023-10-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customereditprofile',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='sellereditprofile',
            old_name='phone',
            new_name='mobile',
        ),
    ]
