# Generated by Django 4.2.5 on 2024-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_society_location_society_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='society',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='society',
            name='society_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
