# Generated by Django 4.2.5 on 2023-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_panchayath_society_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='ward_no',
        ),
        migrations.AddField(
            model_name='society',
            name='subdistrict',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='society',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='society',
            name='location',
            field=models.CharField(default='default_location', max_length=50),
        ),
        migrations.AlterField(
            model_name='society',
            name='society_code',
            field=models.CharField(default='default_value_here', max_length=20),
        ),
    ]
