# Generated by Django 4.2.5 on 2023-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_customgroup_customuser_forget_password_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='True', max_length=15),
        ),
    ]
