# Generated by Django 4.2.5 on 2023-10-30 19:35

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_rename_phone_customer_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('cattle_id', models.AutoField(primary_key=True, serialize=False)),
                ('ear_tag_id', models.IntegerField()),
                ('cattle_type', models.CharField(max_length=10)),
                ('breed_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('colour', models.CharField(max_length=50)),
                ('health_status', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='cattle_profile_photos/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seller')),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='my_default_username', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellereditprofile',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.society'),
        ),
        migrations.CreateModel(
            name='CattleBreed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=50)),
                ('ear_type', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cattle')),
            ],
        ),
    ]
