# Generated by Django 4.2.5 on 2023-11-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_cattle_has_insurance_cattle_has_vaccination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='has_insurance',
        ),
        migrations.RemoveField(
            model_name='cattle',
            name='has_vaccination',
        ),
        migrations.AddField(
            model_name='cattle',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cattle',
            name='vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='farm.cattle'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='cattle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='farm.cattle'),
        ),
    ]
