# Generated by Django 4.2.5 on 2023-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_timestamp_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
