# Generated by Django 4.2.5 on 2023-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_cattle_has_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin')], default='Customer', max_length=15)),
            ],
        ),
    ]
