# Generated by Django 4.2.5 on 2023-11-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_cattle_has_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='sellereditprofile',
            name='cattle_license',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattle_license',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin')], max_length=15),
        ),
    ]
