# Generated by Django 4.2.5 on 2024-03-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_society_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='messagetype',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='society',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='farm.society'),
        ),
    ]
