# Generated by Django 4.2.5 on 2023-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_customer_is_active_seller_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customereditprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customereditprofile',
            name='first_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customereditprofile',
            name='last_name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
