# Generated by Django 4.2.5 on 2023-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_customereditprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customereditprofile',
            name='district',
        ),
    ]
