# Generated by Django 4.2.5 on 2023-10-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='cattleType',
            fields=[
                ('cattle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
