# Generated by Django 4.2.5 on 2024-03-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='messagetype',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='society',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='farm.society'),
        ),
    ]
