# Generated by Django 4.2.5 on 2023-12-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_remove_customereditprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customereditprofile',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='farm.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customereditprofile',
            name='card_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customereditprofile',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customereditprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customereditprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customereditprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
