# Generated by Django 4.2.5 on 2023-11-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_rename_cattle_id_cattletype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='cattle_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farm.cattletype'),
            preserve_default=False,
        ),
    ]
