# Generated by Django 4.2.5 on 2024-02-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_customereditprofile_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Housename', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
