# Generated by Django 4.2.5 on 2023-11-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle',
            old_name='cattle_license',
            new_name='farmer_license',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cattle_license',
            new_name='farmer_license',
        ),
        migrations.RenameField(
            model_name='sellereditprofile',
            old_name='cattle_license',
            new_name='farmer_license',
        ),
    ]
