# Generated by Django 4.2.5 on 2023-11-07 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_rename_cattle_license_cattle_farmer_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='farmer_license',
            field=models.CharField(help_text='Format: Fxxxxx (e.g., F12345)', max_length=7, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_farmer_license', message="Farmer license must be in the format 'Fxxxxx' (e.g., F12345)", regex='^F\\d{5}$')]),
        ),
    ]
