# Generated by Django 4.2.5 on 2024-02-07 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_veterinarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='DoctorId',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
