# Generated by Django 4.2.5 on 2024-02-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_remove_veterinarian_doctorid_veterinarian_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian')], max_length=15),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian')], max_length=15),
        ),
        migrations.CreateModel(
            name='VetEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='vet_profile_photos/')),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('veterinarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.veterinarian')),
            ],
        ),
    ]
