# Generated by Django 4.2.5 on 2023-11-07 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_alter_cattle_farmer_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='farmer_license',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_seller_license', message='Seller license must start with F followed by five digits.', regex='^F\\d{5}$')]),
        ),
    ]
