# Generated by Django 4.2.5 on 2024-02-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_alter_customuser_role_alter_login_details_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinarian',
            old_name='DoctorName',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='veterinarian',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='veterinarian',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='veteditprofile',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='veteditprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='City',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='Housename',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='Specialization',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='specialization',
            field=models.CharField(choices=[('Bovine Practitioner', 'Bovine Practitioner'), ('Reproductive Specialist', 'Reproductive Specialist'), ('Herd Health Veterinarian', 'Herd Health Veterinarian'), ('Cattle Surgery Specialist', 'Cattle Surgery Specialist'), ('Food Animal Veterinarian', 'Food Animal Veterinarian'), ('Veterinary Epidemiologist', 'Veterinary Epidemiologist'), ('Dairy Cattle Veterinarian', 'Dairy Cattle Veterinarian')], default=True, max_length=50),
        ),
    ]
