# Generated by Django 4.2.5 on 2024-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_rename_doctorname_veterinarian_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='doctor_license',
            field=models.CharField(default=True, max_length=10, unique=True),
        ),
    ]
