# Generated by Django 4.2.5 on 2023-10-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_customer_email_customer_firstname_customer_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
