# Generated by Django 4.2.5 on 2024-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_veterinarian_doctor_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_veterinarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
