# Generated by Django 4.2.5 on 2023-10-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_alter_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
