# Generated by Django 4.2.5 on 2023-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_cattle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellereditprofile',
            name='pin_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
