# Generated by Django 4.2.5 on 2023-10-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_remove_customer_email_alter_seller_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
    ]
