# Generated by Django 4.2.5 on 2024-02-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_deliveryboy_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('DeliveryBoy', 'DeliveryBoy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('DeliveryBoy', 'DeliveryBoy')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
