# Generated by Django 4.2.5 on 2023-11-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_sellereditprofile_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellereditprofile',
            name='society',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farm.society'),
        ),
    ]
