# Generated by Django 4.2.5 on 2023-11-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_alter_sellereditprofile_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellereditprofile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farm.society'),
        ),
    ]
