# Generated by Django 4.2.5 on 2024-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_veteditprofile_start_year_veterinarian_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteditprofile',
            name='doctor_license',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='veteditprofile',
            name='doctor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veteditprofile',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
