# Generated by Django 4.2.5 on 2023-11-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_alter_sellereditprofile_farmer_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattletype',
            name='name',
            field=models.CharField(choices=[('cow', 'COW'), ('goat', 'GOAT'), ('buffalo', 'BUFFALO')], default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
