# Generated by Django 4.2.5 on 2024-02-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptom',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='appointment_no',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='farm.seller'),
        ),
    ]
