# Generated by Django 4.2.5 on 2024-02-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_rename_symptom_appointment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
