# Generated by Django 4.2.5 on 2023-10-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='housename',
        ),
    ]
