# Generated by Django 4.2.5 on 2024-02-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_appointment_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
