# Generated by Django 4.2.5 on 2023-10-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_remove_customer_district_remove_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customeredit',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
