# Generated by Django 4.2.5 on 2024-02-21 04:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_alter_appointment_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_no',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farm.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='seller_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
