# Generated by Django 4.2.5 on 2024-02-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='seller_token',
        ),
    ]
