# Generated by Django 4.2.5 on 2024-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0027_remove_appointment_seller_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
