# Generated by Django 4.2.5 on 2024-02-27 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_license', models.ImageField(blank=True, null=True, upload_to='driving_license/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('DeliveryBoy', 'Delivery Boy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('DeliveryBoy', 'Delivery Boy')], max_length=15),
        ),
        migrations.CreateModel(
            name='DeliveryBoyEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(blank=True, default=None, null=True)),
                ('driving_license', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='delivery_boy_profile_photos/')),
                ('delivery_boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm.deliveryboy')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
