# Generated by Django 4.2.5 on 2023-10-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_alter_customer_user_alter_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('card_number', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Your_Profile/')),
            ],
        ),
        migrations.CreateModel(
            name='IFSCCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('accno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerEditProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('rationcard_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('acc_no', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='seller_profile_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('subdistrict', models.CharField(max_length=50)),
                ('panchayath', models.CharField(max_length=50)),
                ('ward_no', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societies', to='farm.sellereditprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='selleredit',
            name='user',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerEdit',
        ),
        migrations.DeleteModel(
            name='SellerEdit',
        ),
        migrations.AddField(
            model_name='sellereditprofile',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='farm.society'),
        ),
        migrations.AddField(
            model_name='ifsccode',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifsccodes', to='farm.sellereditprofile'),
        ),
    ]
