# Generated by Django 4.2.5 on 2024-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_deliveryboy_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_boy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('Delivery Boy', 'Delivery Boy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Seller', 'Seller'), ('Admin', 'Admin'), ('Veterinarian', 'Veterinarian'), ('Delivery Boy', 'Delivery Boy')], max_length=15),
        ),
    ]
