# Generated by Django 4.2.5 on 2024-02-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_customuser_is_delivery_boy_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
