# Generated by Django 4.2.5 on 2024-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0032_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryboyeditprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellereditprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
