# Generated by Django 4.2.5 on 2024-03-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0034_remove_deliveryboyeditprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='status',
        ),
    ]
